// Top 50 US cities for localized renovation content
// Each entry generates SEO-optimized city pages with localized pricing, permit info, and climate context

export interface CityData {
  slug: string;
  name: string;
  state: string;
  stateAbbr: string;
  population: number;
  region: 'Northeast' | 'Midwest' | 'South' | 'West' | 'Pacific';
  costIndex: number;
  description: string;
  permitAuthority: string;
  permitUrl: string;
  climateZones: string[];
  medianHomeValue: string;
  typicalSqft: string;
  commonArchitecturalStyles: string[];
  featuredGuides: string[];
  imagePrompt: string;
}

export const TOP_50_CITIES: CityData[] = [
  {
    slug: 'new-york-city', name: 'New York City', state: 'New York', stateAbbr: 'NY',
    population: 8336817, region: 'Northeast', costIndex: 1.85,
    description: 'New York City is the most densely populated major city in the US, with a massive stock of pre-war and post-war apartment buildings, townhouses, and brownstones. Renovation work in NYC typically requires strict DOB permitting, especially for structural, plumbing, or electrical changes. Co-op and condo board approvals add an extra layer of complexity beyond standard permits.',
    permitAuthority: 'NYC Department of Buildings (DOB)', permitUrl: 'https://www.nyc.gov/site/buildings/index.page',
    climateZones: ['Cold humid winter', 'Hot humid summer', 'Zone 4'],
    medianHomeValue: '$685,000', typicalSqft: '900',
    commonArchitecturalStyles: ['Pre-war', 'Brownstone', 'Modern high-rise', 'Townhouse'],
    featuredGuides: ['kitchen-remodel-cost', 'bathroom-remodel-cost', 'interior-painting-cost'],
    imagePrompt: 'A Brooklyn brownstone rowhome with classic brick facade and stoop during a sunny day in NYC',
  },
  {
    slug: 'los-angeles', name: 'Los Angeles', state: 'California', stateAbbr: 'CA',
    population: 3898747, region: 'West', costIndex: 1.65,
    description: 'Los Angeles is a sprawling metro area with a mix of single-family homes, Spanish-style bungalows, mid-century moderns, and new developments. Renovation in LA requires LADBS permits for structural work, additions, and certain mechanical systems. The mild year-round climate extends the construction season, and seismic retrofitting requirements often add cost to major remodels.',
    permitAuthority: 'Los Angeles Department of Building and Safety (LADBS)', permitUrl: 'https://www.ladbs.org/',
    climateZones: ['Mediterranean', 'Mild winter', 'Warm summer', 'Zone 3'],
    medianHomeValue: '$875,000', typicalSqft: '1,400',
    commonArchitecturalStyles: ['Spanish Colonial', 'Mid-century Modern', 'Bungalow', 'Ranch'],
    featuredGuides: ['kitchen-remodel-cost', 'deck-build-cost', 'interior-painting-cost'],
    imagePrompt: 'A Spanish Colonial revival home with red tile roof and stucco exterior in Los Angeles',
  },
  {
    slug: 'chicago', name: 'Chicago', state: 'Illinois', stateAbbr: 'IL',
    population: 2746388, region: 'Midwest', costIndex: 1.25,
    description: 'Chicago is known for its brick bungalows, graystone two-flats, vintage high-rises, and new construction condos. The city requires permits through the Department of Buildings for most renovation work beyond cosmetic changes. Cold winters mean a shorter outdoor construction season, and many older buildings have lead paint or knob-and-tube wiring considerations.',
    permitAuthority: 'Chicago Department of Buildings', permitUrl: 'https://www.chicago.gov/city/en/depts/bldgs.html',
    climateZones: ['Cold winter', 'Hot humid summer', 'Zone 5'],
    medianHomeValue: '$315,000', typicalSqft: '1,300',
    commonArchitecturalStyles: ['Bungalow', 'Greystone', 'Victorian', 'Two-flat'],
    featuredGuides: ['bathroom-remodel-cost', 'roof-replacement-cost', 'interior-painting-cost'],
    imagePrompt: 'A classic Chicago brick bungalow with front porch and green lawn in summer',
  },
  {
    slug: 'houston', name: 'Houston', state: 'Texas', stateAbbr: 'TX',
    population: 2304580, region: 'South', costIndex: 0.95,
    description: 'Houston has a housing stock dominated by single-family homes and townhouses on expansive lots. The Houston Permitting Center handles city permits. No zoning laws mean a diverse mix of property types. Foundation issues from expansive clay soils are a common hidden cost in renovation projects.',
    permitAuthority: 'Houston Permitting Center', permitUrl: 'https://www.houstonpermittingcenter.org/',
    climateZones: ['Hot humid', 'Mild winter', 'Hurricane risk', 'Zone 4'],
    medianHomeValue: '$290,000', typicalSqft: '1,800',
    commonArchitecturalStyles: ['Ranch', 'Contemporary', 'Colonial', 'Mediterranean'],
    featuredGuides: ['roof-replacement-cost', 'interior-painting-cost', 'deck-build-cost'],
    imagePrompt: 'A stone and brick Texas ranch style home with large front yard in Houston',
  },
  {
    slug: 'phoenix', name: 'Phoenix', state: 'Arizona', stateAbbr: 'AZ',
    population: 1608139, region: 'West', costIndex: 1.05,
    description: 'Phoenix has a large stock of stucco ranch homes, Spanish revival properties, and new master-planned communities. Extreme summer heat affects construction scheduling, and energy efficiency upgrades are a major consideration. AC replacement costs are a frequent project driver for Valley homeowners.',
    permitAuthority: 'City of Phoenix Planning & Development', permitUrl: 'https://www.phoenix.gov/pdd',
    climateZones: ['Hot arid', 'Mild winter', 'Extreme summer', 'Zone 3'],
    medianHomeValue: '$425,000', typicalSqft: '1,600',
    commonArchitecturalStyles: ['Spanish Revival', 'Ranch', 'Southwest Contemporary'],
    featuredGuides: ['roof-replacement-cost', 'interior-painting-cost', 'deck-build-cost'],
    imagePrompt: 'A Southwestern style home with stucco exterior and red tile roof in Phoenix',
  },
  {
    slug: 'philadelphia', name: 'Philadelphia', state: 'Pennsylvania', stateAbbr: 'PA',
    population: 1603797, region: 'Northeast', costIndex: 1.15,
    description: 'Philadelphia has a vast inventory of rowhomes, trinity houses, and early 20th-century brick buildings. The Department of Licenses and Inspections (L&I) oversees permits. Older housing stock means lead paint, knob-and-tube wiring, and aging plumbing are frequent surprises during renovations.',
    permitAuthority: 'Philadelphia Department of Licenses & Inspections', permitUrl: 'https://www.phila.gov/departments/licenses-and-inspections/',
    climateZones: ['Cold winter', 'Humid summer', 'Zone 6'],
    medianHomeValue: '$235,000', typicalSqft: '1,200',
    commonArchitecturalStyles: ['Rowhome', 'Trinity', 'Victorian', 'Colonial'],
    featuredGuides: ['bathroom-remodel-cost', 'interior-painting-cost', 'kitchen-remodel-cost'],
    imagePrompt: 'A row of classic Philadelphia brick rowhomes with marble steps and street trees',
  },
  {
    slug: 'san-antonio', name: 'San Antonio', state: 'Texas', stateAbbr: 'TX',
    population: 1547253, region: 'South', costIndex: 0.90,
    description: 'San Antonio blends historic Spanish mission architecture with sprawling suburban developments. The Development Services Department processes permits. Foundation movement from clay soils and summer heat are common cost factors.',
    permitAuthority: 'San Antonio Development Services Department', permitUrl: 'https://www.sanantonio.gov/DSD',
    climateZones: ['Hot humid', 'Mild winter', 'Zone 4'],
    medianHomeValue: '$275,000', typicalSqft: '1,700',
    commonArchitecturalStyles: ['Spanish Colonial', 'Ranch', 'Contemporary'],
    featuredGuides: ['roof-replacement-cost', 'interior-painting-cost'],
    imagePrompt: 'A Spanish Colonial style home with archways and red tile details in San Antonio',
  },
  {
    slug: 'san-diego', name: 'San Diego', state: 'California', stateAbbr: 'CA',
    population: 1386932, region: 'Pacific', costIndex: 1.55,
    description: 'San Diego offers Spanish and Craftsman bungalows, mid-century homes, and newer coastal construction. The mild climate allows year-round construction, but coastal commission requirements can add time and cost near the coastline.',
    permitAuthority: 'San Diego Development Services Department', permitUrl: 'https://www.sandiego.gov/development-services',
    climateZones: ['Mediterranean', 'Mild year-round', 'Zone 3'],
    medianHomeValue: '$825,000', typicalSqft: '1,300',
    commonArchitecturalStyles: ['Spanish Revival', 'Craftsman', 'Mid-century Modern'],
    featuredGuides: ['deck-build-cost', 'interior-painting-cost'],
    imagePrompt: 'A Craftsman bungalow with front porch and native landscaping in San Diego',
  },
  {
    slug: 'dallas', name: 'Dallas', state: 'Texas', stateAbbr: 'TX',
    population: 1304379, region: 'South', costIndex: 1.00,
    description: 'Dallas has a mix of historic homes in neighborhoods like M Streets and Lakewood plus sprawling new subdivisions. Clay soils and foundation issues are the most common hidden cost factors for DFW homeowners.',
    permitAuthority: 'Dallas Development Services Department', permitUrl: 'https://dallascityhall.com/departments/sustainabledevelopment/Pages/default.aspx',
    climateZones: ['Hot humid', 'Mild winter', 'Zone 4'],
    medianHomeValue: '$350,000', typicalSqft: '1,800',
    commonArchitecturalStyles: ['Ranch', 'Tudor', 'Contemporary', 'Craftsman'],
    featuredGuides: ['roof-replacement-cost', 'interior-painting-cost'],
    imagePrompt: 'A Tudor style home with brick exterior and manicured lawn in Dallas',
  },
  {
    slug: 'san-jose', name: 'San Jose', state: 'California', stateAbbr: 'CA',
    population: 1013240, region: 'Pacific', costIndex: 1.75,
    description: 'San Jose is the heart of Silicon Valley with ranch-style homes, Eichler mid-century moderns, and new infill developments. High property values drive renovation costs upward. Energy efficiency mandates (Title 24) and seismic retrofitting are common additional expenses.',
    permitAuthority: 'San Jose Building Division', permitUrl: 'https://www.sanjoseca.gov/your-government/departments/planning-building-code-enforcement',
    climateZones: ['Mediterranean', 'Mild', 'Zone 3'],
    medianHomeValue: '$1,350,000', typicalSqft: '1,500',
    commonArchitecturalStyles: ['Ranch', 'Eichler/Mid-century', 'Contemporary'],
    featuredGuides: ['kitchen-remodel-cost', 'bathroom-remodel-cost'],
    imagePrompt: 'An Eichler mid-century modern home with clean lines and flat roof in San Jose',
  },
  {
    slug: 'austin', name: 'Austin', state: 'Texas', stateAbbr: 'TX',
    population: 964177, region: 'South', costIndex: 1.15,
    description: 'Austin is one of the fastest-growing metros with housing ranging from historic bungalows in central neighborhoods to new build-to-rent communities in the suburbs. Foundation issues from clay soil and summer heat are top concerns.',
    permitAuthority: 'Austin Development Services Department', permitUrl: 'https://www.austintexas.gov/department/development-services-department',
    climateZones: ['Hot humid', 'Mild winter', 'Zone 4'],
    medianHomeValue: '$525,000', typicalSqft: '1,600',
    commonArchitecturalStyles: ['Bungalow', 'Contemporary', 'Mid-century', 'Craftsman'],
    featuredGuides: ['deck-build-cost', 'roof-replacement-cost'],
    imagePrompt: 'A Craftsman bungalow with front porch and oak trees in Austin',
  },
  {
    slug: 'jacksonville', name: 'Jacksonville', state: 'Florida', stateAbbr: 'FL',
    population: 949611, region: 'South', costIndex: 0.95,
    description: 'Jacksonville spans beachfront condos, historic riverside neighborhoods, and suburban subdivisions. Flood zones, hurricane preparedness, and wind mitigation requirements affect renovation costs significantly.',
    permitAuthority: 'Jacksonville Building Inspection Division', permitUrl: 'https://www.jacksonville.gov/departments/neighborhoods/building-inspection-division.aspx',
    climateZones: ['Hot humid', 'Mild winter', 'Hurricane risk', 'Zone 4'],
    medianHomeValue: '$335,000', typicalSqft: '1,700',
    commonArchitecturalStyles: ['Colonial', 'Ranch', 'Contemporary', 'Mediterranean'],
    featuredGuides: ['roof-replacement-cost'],
    imagePrompt: 'A Colonial revival home with white columns near the coast in Jacksonville',
  },
  {
    slug: 'fort-worth', name: 'Fort Worth', state: 'Texas', stateAbbr: 'TX',
    population: 935508, region: 'South', costIndex: 0.95,
    description: 'Fort Worth combines Western heritage with modern suburban growth. The housing stock includes historic Craftsman bungalows, ranches from the 50s-70s, and new construction. Foundation repairs are a common need.',
    permitAuthority: 'Fort Worth Development Services Department', permitUrl: 'https://www.fortworthtexas.gov/departments/development-services',
    climateZones: ['Hot humid', 'Mild winter', 'Zone 4'],
    medianHomeValue: '$325,000', typicalSqft: '1,700',
    commonArchitecturalStyles: ['Craftsman', 'Ranch', 'Tudor', 'Contemporary'],
    featuredGuides: ['roof-replacement-cost'],
    imagePrompt: 'A Craftsman bungalow with stone accents and large covered porch in Fort Worth',
  },
  {
    slug: 'columbus', name: 'Columbus', state: 'Ohio', stateAbbr: 'OH',
    population: 905748, region: 'Midwest', costIndex: 0.90,
    description: 'Columbus has a mix of Craftsman bungalows in historic neighborhoods like German Village and mid-century ranches. Cold winters create seasonal constraints for outdoor renovation work.',
    permitAuthority: 'Columbus Department of Building and Zoning Services', permitUrl: 'https://www.columbus.gov/bz/',
    climateZones: ['Cold winter', 'Humid summer', 'Zone 5'],
    medianHomeValue: '$295,000', typicalSqft: '1,400',
    commonArchitecturalStyles: ['Craftsman', 'Ranch', 'Victorian', 'Cape Cod'],
    featuredGuides: ['bathroom-remodel-cost', 'interior-painting-cost'],
    imagePrompt: 'A brick German Village style home with cottage garden in Columbus, Ohio',
  },
  {
    slug: 'charlotte', name: 'Charlotte', state: 'North Carolina', stateAbbr: 'NC',
    population: 897720, region: 'South', costIndex: 1.00,
    description: 'Charlotte is one of the fastest-growing cities in the Southeast with historic neighborhoods, established suburbs, and new construction. Mold and humidity concerns are common in basements. The Charlotte-Mecklenburg Building Standards handles permits.',
    permitAuthority: 'Charlotte-Mecklenburg Building Standards', permitUrl: 'https://www.mecknc.gov/LUESA/CodeEnforcement/Pages/default.aspx',
    climateZones: ['Humid subtropical', 'Mild winter', 'Hot summer', 'Zone 4'],
    medianHomeValue: '$375,000', typicalSqft: '1,600',
    commonArchitecturalStyles: ['Colonial', 'Craftsman', 'Ranch', 'Contemporary'],
    featuredGuides: ['kitchen-remodel-cost', 'interior-painting-cost'],
    imagePrompt: 'A Craftsman style home with front porch and hardwood trees in Charlotte',
  },
  {
    slug: 'indianapolis', name: 'Indianapolis', state: 'Indiana', stateAbbr: 'IN',
    population: 887632, region: 'Midwest', costIndex: 0.85,
    description: 'Indianapolis offers affordable housing with historic homes, mid-century ranches, and new subdivisions. The Department of Business and Neighborhood Services handles permits. Cold winters and humid summers create seasonal work patterns.',
    permitAuthority: 'Indianapolis Department of Business and Neighborhood Services', permitUrl: 'https://www.indy.gov/activity/get-a-permit',
    climateZones: ['Cold winter', 'Humid summer', 'Zone 5'],
    medianHomeValue: '$240,000', typicalSqft: '1,500',
    commonArchitecturalStyles: ['Craftsman', 'Ranch', 'Victorian', 'Cape Cod'],
    featuredGuides: ['interior-painting-cost'],
    imagePrompt: 'A brick Colonial style home with white columns in Indianapolis',
  },
  {
    slug: 'san-francisco', name: 'San Francisco', state: 'California', stateAbbr: 'CA',
    population: 873965, region: 'Pacific', costIndex: 2.10,
    description: 'San Francisco has some of the highest renovation costs in the country, driven by strict DBI permitting, high labor rates, and dense urban work challenges. Seismic retrofitting, Title 24 energy codes, and historic preservation rules add significant cost.',
    permitAuthority: 'San Francisco Department of Building Inspection (DBI)', permitUrl: 'https://sfdbi.org/',
    climateZones: ['Mediterranean', 'Cool summer', 'Mild winter', 'Zone 3'],
    medianHomeValue: '$1,400,000', typicalSqft: '1,100',
    commonArchitecturalStyles: ['Victorian', 'Edwardian', 'Mid-century', 'Contemporary'],
    featuredGuides: ['kitchen-remodel-cost', 'bathroom-remodel-cost'],
    imagePrompt: 'A row of classic San Francisco Painted Ladies Victorian homes on a hill',
  },
  {
    slug: 'seattle', name: 'Seattle', state: 'Washington', stateAbbr: 'WA',
    population: 737015, region: 'Pacific', costIndex: 1.60,
    description: 'Seattle has a mix of Craftsman bungalows, mid-century homes, and new high-rise condos. The SDCI handles permits. Rain and moisture concerns affect exterior work timing, and hillside properties often require geotechnical engineering.',
    permitAuthority: 'Seattle Department of Construction & Inspections', permitUrl: 'https://www.seattle.gov/sdci',
    climateZones: ['Marine West Coast', 'Cool wet winter', 'Mild summer', 'Zone 4'],
    medianHomeValue: '$825,000', typicalSqft: '1,500',
    commonArchitecturalStyles: ['Craftsman', 'Mid-century', 'Northwest Contemporary'],
    featuredGuides: ['deck-build-cost', 'interior-painting-cost'],
    imagePrompt: 'A Craftsman home with wood siding and evergreen landscaping in Seattle',
  },
  {
    slug: 'denver', name: 'Denver', state: 'Colorado', stateAbbr: 'CO',
    population: 715522, region: 'West', costIndex: 1.25,
    description: 'Denver has Victorian homes in historic neighborhoods and sprawling suburban developments. Semi-arid climate means dry conditions but foundation issues from expansive clay and freeze-thaw cycles are common.',
    permitAuthority: 'Denver Community Planning & Development', permitUrl: 'https://www.denvergov.org/communityplanninganddevelopment',
    climateZones: ['Semi-arid', 'Cold winter', 'Hot summer', 'Zone 5'],
    medianHomeValue: '$575,000', typicalSqft: '1,600',
    commonArchitecturalStyles: ['Victorian', 'Mid-century', 'Denver Square', 'Contemporary'],
    featuredGuides: ['roof-replacement-cost', 'deck-build-cost'],
    imagePrompt: 'A Victorian style home with mountain views in Denver',
  },
  {
    slug: 'nashville', name: 'Nashville', state: 'Tennessee', stateAbbr: 'TN',
    population: 689447, region: 'South', costIndex: 1.10,
    description: 'Nashville has historic homes in neighborhoods like East Nashville and Germantown plus expanding suburbs. No state income tax and a robust economy drive renovation demand.',
    permitAuthority: 'Metro Nashville Codes & Building Safety', permitUrl: 'https://www.nashville.gov/departments/codes',
    climateZones: ['Humid subtropical', 'Mild winter', 'Hot summer', 'Zone 4'],
    medianHomeValue: '$450,000', typicalSqft: '1,500',
    commonArchitecturalStyles: ['Craftsman', 'Bungalow', 'Ranch', 'Victorian'],
    featuredGuides: ['interior-painting-cost'],
    imagePrompt: 'A Craftsman bungalow with rocking chair front porch in Nashville',
  },
  {
    slug: 'oklahoma-city', name: 'Oklahoma City', state: 'Oklahoma', stateAbbr: 'OK',
    population: 681054, region: 'South', costIndex: 0.85,
    description: 'Oklahoma City offers affordable housing with historic homes, mid-century ranches, and growing suburban development. Tornado risk means storm shelter and wind mitigation are significant renovation considerations.',
    permitAuthority: 'Oklahoma City Development Services Division', permitUrl: 'https://www.okc.gov/departments/development-services',
    climateZones: ['Humid subtropical', 'Hot summer', 'Severe storms', 'Zone 5'],
    medianHomeValue: '$215,000', typicalSqft: '1,600',
    commonArchitecturalStyles: ['Ranch', 'Colonial', 'Craftsman', 'Contemporary'],
    featuredGuides: [],
    imagePrompt: 'A Ranch style home with stone veneer and large front yard in Oklahoma City',
  },
  {
    slug: 'el-paso', name: 'El Paso', state: 'Texas', stateAbbr: 'TX',
    population: 678815, region: 'South', costIndex: 0.80,
    description: 'El Paso sits at the Texas-Mexico border with Southwestern and Spanish colonial architecture. The desert climate means extreme summer heat and mild winters, affecting construction scheduling.',
    permitAuthority: 'El Paso Building and Permits Division', permitUrl: 'https://www.elpasotexas.gov/development-services/',
    climateZones: ['Hot arid', 'Mild winter', 'Extreme summer', 'Zone 3'],
    medianHomeValue: '$185,000', typicalSqft: '1,500',
    commonArchitecturalStyles: ['Spanish Colonial', 'Ranch', 'Southwest Contemporary'],
    featuredGuides: [],
    imagePrompt: 'A Territorial style home with adobe walls and portal porch in El Paso',
  },
  {
    slug: 'washington-dc', name: 'Washington DC', state: 'District of Columbia', stateAbbr: 'DC',
    population: 678572, region: 'Northeast', costIndex: 1.55,
    description: 'Washington DC has historic rowhomes in Capitol Hill and Georgetown plus growing luxury condos. Historic preservation review is required for exterior work in many neighborhoods. Rowhome renovations face shared wall agreements and limited staging space.',
    permitAuthority: 'DC Department of Buildings', permitUrl: 'https://dob.dc.gov/',
    climateZones: ['Humid subtropical', 'Cold winter', 'Hot summer', 'Zone 5'],
    medianHomeValue: '$650,000', typicalSqft: '1,200',
    commonArchitecturalStyles: ['Rowhome', 'Victorian', 'Federal', 'Contemporary'],
    featuredGuides: ['kitchen-remodel-cost', 'bathroom-remodel-cost'],
    imagePrompt: 'A row of Federal style rowhomes with brick facades and black shutters in Washington DC',
  },
  {
    slug: 'boston', name: 'Boston', state: 'Massachusetts', stateAbbr: 'MA',
    population: 675647, region: 'Northeast', costIndex: 1.70,
    description: 'Boston has triple-deckers, historic brownstones, and condos. The ISD manages permits. Strict historical commissions, challenging parking logistics, and old building infrastructure are major cost drivers.',
    permitAuthority: 'Boston Inspectional Services Department', permitUrl: 'https://www.boston.gov/departments/inspectional-services',
    climateZones: ['Cold winter', 'Humid summer', 'Zone 6'],
    medianHomeValue: '$690,000', typicalSqft: '1,000',
    commonArchitecturalStyles: ['Triple-decker', 'Brownstone', 'Victorian', 'Colonial'],
    featuredGuides: ['interior-painting-cost', 'bathroom-remodel-cost'],
    imagePrompt: 'A Boston triple-decker home with wooden porches and bay windows in South Boston',
  },
  {
    slug: 'detroit', name: 'Detroit', state: 'Michigan', stateAbbr: 'MI',
    population: 632464, region: 'Midwest', costIndex: 0.75,
    description: 'Detroit has a unique housing market with historic homes in neighborhoods like Indian Village and Woodbridge alongside a large stock of classic bungalows. BSEED handles permits. Many older homes need significant mechanical, roof, and foundation work.',
    permitAuthority: 'Detroit BSEED', permitUrl: 'https://detroitmi.gov/departments/building-safety-engineering-and-environmental-department',
    climateZones: ['Cold winter', 'Humid summer', 'Zone 6'],
    medianHomeValue: '$105,000', typicalSqft: '1,300',
    commonArchitecturalStyles: ['Craftsman', 'Bungalow', 'Victorian', 'Mid-century'],
    featuredGuides: ['interior-painting-cost'],
    imagePrompt: 'A brick bungalow with wide front porch in Detroit',
  },
  {
    slug: 'memphis', name: 'Memphis', state: 'Tennessee', stateAbbr: 'TN',
    population: 628127, region: 'South', costIndex: 0.80,
    description: 'Memphis has a mix of historic homes in Midtown and East Memphis neighborhoods plus growing suburbs. The Office of Construction Code Enforcement handles permits. Humidity and mold concerns are common renovation drivers.',
    permitAuthority: 'Memphis Office of Construction Code Enforcement', permitUrl: 'https://www.memphistn.gov/government/codeenforcement/',
    climateZones: ['Humid subtropical', 'Hot summer', 'Mild winter', 'Zone 4'],
    medianHomeValue: '$165,000', typicalSqft: '1,500',
    commonArchitecturalStyles: ['Colonial', 'Ranch', 'Bungalow', 'Mid-century'],
    featuredGuides: [],
    imagePrompt: 'A Colonial revival home with columns and magnolia trees in Memphis',
  },
  {
    slug: 'louisville', name: 'Louisville', state: 'Kentucky', stateAbbr: 'KY',
    population: 624444, region: 'South', costIndex: 0.85,
    description: 'Louisville has historic shotgun homes and Victorian houses in Old Louisville alongside mid-century ranches and new construction. The Department of Codes and Regulations handles permits.',
    permitAuthority: 'Louisville Department of Codes and Regulations', permitUrl: 'https://louisvilleky.gov/government/codes-regulations',
    climateZones: ['Humid subtropical', 'Cold winter', 'Hot summer', 'Zone 5'],
    medianHomeValue: '$225,000', typicalSqft: '1,400',
    commonArchitecturalStyles: ['Victorian', 'Shotgun', 'Bungalow', 'Ranch'],
    featuredGuides: [],
    imagePrompt: 'A Victorian home with gingerbread trim in Old Louisville',
  },
  {
    slug: 'portland', name: 'Portland', state: 'Oregon', stateAbbr: 'OR',
    population: 635240, region: 'Pacific', costIndex: 1.40,
    description: 'Portland has Craftsman bungalows, Victorian homes, mid-century ranches, and new infill construction. The Bureau of Development Services handles permits. Rain and environmental regulations affect exterior work timing.',
    permitAuthority: 'Portland Bureau of Development Services', permitUrl: 'https://www.portland.gov/bds',
    climateZones: ['Marine West Coast', 'Cool wet winter', 'Mild summer', 'Zone 4'],
    medianHomeValue: '$515,000', typicalSqft: '1,400',
    commonArchitecturalStyles: ['Craftsman', 'Victorian', 'Mid-century', 'Northwest Contemporary'],
    featuredGuides: ['deck-build-cost'],
    imagePrompt: 'A Craftsman bungalow with natural wood siding and Japanese maple in Portland',
  },
  {
    slug: 'las-vegas', name: 'Las Vegas', state: 'Nevada', stateAbbr: 'NV',
    population: 646653, region: 'West', costIndex: 1.05,
    description: 'Las Vegas has a large stock of stucco homes, Spanish-style properties, and master-planned communities. The Building Division handles permits. Extreme desert heat and low humidity affect HVAC requirements and construction scheduling.',
    permitAuthority: 'Las Vegas Building Division', permitUrl: 'https://www.lasvegasnevada.gov/Residents/Building-Permits',
    climateZones: ['Hot arid', 'Mild winter', 'Extreme summer', 'Zone 3'],
    medianHomeValue: '$375,000', typicalSqft: '1,600',
    commonArchitecturalStyles: ['Spanish Revival', 'Ranch', 'Southwest Contemporary', 'Mediterranean'],
    featuredGuides: [],
    imagePrompt: 'A Mediterranean style stucco home with tile roof in Las Vegas desert landscape',
  },
  {
    slug: 'baltimore', name: 'Baltimore', state: 'Maryland', stateAbbr: 'MD',
    population: 585708, region: 'Northeast', costIndex: 1.00,
    description: 'Baltimore has a large stock of rowhomes, from historic Federal-style in Fells Point to Formstone-covered in Hampden. DHCD handles permits. Older housing means lead paint, aging plumbing, and historic district restrictions.',
    permitAuthority: 'Baltimore Department of Housing & Community Development', permitUrl: 'https://dhcd.baltimorecity.gov/',
    climateZones: ['Cold winter', 'Humid summer', 'Zone 6'],
    medianHomeValue: '$210,000', typicalSqft: '1,200',
    commonArchitecturalStyles: ['Rowhome', 'Federal', 'Victorian', 'Colonial'],
    featuredGuides: ['interior-painting-cost'],
    imagePrompt: 'Classic Baltimore rowhomes with marble steps and Formstone fronts',
  },
  {
    slug: 'milwaukee', name: 'Milwaukee', state: 'Wisconsin', stateAbbr: 'WI',
    population: 569330, region: 'Midwest', costIndex: 0.85,
    description: 'Milwaukee has historic neighborhoods with Victorian and Craftsman homes plus bungalows and duplexes. DNS handles permits. Harsh winters create a compressed outdoor construction season.',
    permitAuthority: 'Milwaukee Department of Neighborhood Services', permitUrl: 'https://city.milwaukee.gov/DNS',
    climateZones: ['Cold winter', 'Humid summer', 'Zone 6'],
    medianHomeValue: '$175,000', typicalSqft: '1,300',
    commonArchitecturalStyles: ['Victorian', 'Craftsman', 'Bungalow', 'Cape Cod'],
    featuredGuides: [],
    imagePrompt: 'A brick Craftsman home with covered porch in Milwaukee',
  },
  {
    slug: 'albuquerque', name: 'Albuquerque', state: 'New Mexico', stateAbbr: 'NM',
    population: 562599, region: 'West', costIndex: 0.90,
    description: 'Albuquerque blends Pueblo and Spanish colonial architecture with mid-century ranches and new developments. The Planning Department handles permits. High desert climate means dry conditions and significant temperature swings.',
    permitAuthority: 'Albuquerque Planning Department', permitUrl: 'https://www.cabq.gov/planning',
    climateZones: ['High desert', 'Cold winter', 'Hot summer', 'Zone 4'],
    medianHomeValue: '$290,000', typicalSqft: '1,500',
    commonArchitecturalStyles: ['Pueblo Revival', 'Spanish Colonial', 'Ranch', 'Territorial'],
    featuredGuides: [],
    imagePrompt: 'A Pueblo Revival style home with flat roof and vigas in Albuquerque with Sandia Mountains background',
  },
  {
    slug: 'tucson', name: 'Tucson', state: 'Arizona', stateAbbr: 'AZ',
    population: 542629, region: 'West', costIndex: 0.95,
    description: 'Tucson has Sonoran-style architecture, mid-century homes, and growing master-planned communities. Development Services handles permits. Extreme heat and monsoon season affect renovation scheduling.',
    permitAuthority: 'Tucson Development Services Department', permitUrl: 'https://www.tucsonaz.gov/departments/development-services',
    climateZones: ['Hot arid', 'Mild winter', 'Monsoon season', 'Zone 3'],
    medianHomeValue: '$310,000', typicalSqft: '1,500',
    commonArchitecturalStyles: ['Spanish Colonial', 'Pueblo Revival', 'Ranch', 'Mid-century'],
    featuredGuides: [],
    imagePrompt: 'A Spanish Colonial home with terracotta roof and cactus garden in Tucson',
  },
  {
    slug: 'fresno', name: 'Fresno', state: 'California', stateAbbr: 'CA',
    population: 542107, region: 'Pacific', costIndex: 0.95,
    description: 'Fresno is the economic hub of the Central Valley with housing from historic Tower District homes to suburban subdivisions. Development & Resource Management handles permits.',
    permitAuthority: 'Fresno Development & Resource Management', permitUrl: 'https://www.fresno.gov/darm/',
    climateZones: ['Mediterranean continental', 'Hot summer', 'Mild winter', 'Zone 4'],
    medianHomeValue: '$345,000', typicalSqft: '1,600',
    commonArchitecturalStyles: ['Ranch', 'Craftsman', 'Mid-century', 'Contemporary'],
    featuredGuides: [],
    imagePrompt: 'A mid-century ranch home with front lawn in Fresno',
  },
  {
    slug: 'sacramento', name: 'Sacramento', state: 'California', stateAbbr: 'CA',
    population: 524943, region: 'Pacific', costIndex: 1.15,
    description: 'Sacramento has a mix of historic homes in Midtown and East Sacramento plus sprawling suburban communities. Community Development handles permits. Hot summers and mild winters allow year-round construction.',
    permitAuthority: 'Sacramento Community Development Department', permitUrl: 'https://www.cityofsacramento.org/Community-Development',
    climateZones: ['Mediterranean', 'Hot summer', 'Mild winter', 'Zone 4'],
    medianHomeValue: '$450,000', typicalSqft: '1,500',
    commonArchitecturalStyles: ['Craftsman', 'Ranch', 'Victorian', 'Contemporary'],
    featuredGuides: [],
    imagePrompt: 'A Craftsman bungalow with front porch and tree-lined street in Sacramento',
  },
  {
    slug: 'mesa', name: 'Mesa', state: 'Arizona', stateAbbr: 'AZ',
    population: 509475, region: 'West', costIndex: 0.95,
    description: 'Mesa is a fast-growing Phoenix suburb with ranch-style homes, Spanish revival properties, and extensive master-planned communities. Extreme summer heat and energy efficiency upgrades are top considerations for renovation projects.',
    permitAuthority: 'Mesa Development Services', permitUrl: 'https://www.mesaaz.gov/business/development-services',
    climateZones: ['Hot arid', 'Mild winter', 'Extreme summer', 'Zone 3'],
    medianHomeValue: '$385,000', typicalSqft: '1,700',
    commonArchitecturalStyles: ['Ranch', 'Spanish Revival', 'Southwest Contemporary', 'Mid-century'],
    featuredGuides: [],
    imagePrompt: 'A Southwestern ranch style home with desert landscaping and mountain backdrop in Mesa',
  },
  {
    slug: 'kansas-city', name: 'Kansas City', state: 'Missouri', stateAbbr: 'MO',
    population: 508090, region: 'Midwest', costIndex: 0.90,
    description: 'Kansas City has historic neighborhoods like the Country Club District, mid-century ranches, and booming new suburbs on both sides of the state line. The City Planning and Development Department handles permits. Freeze-thaw cycles and foundation shifting are common concerns.',
    permitAuthority: 'Kansas City City Planning and Development Department', permitUrl: 'https://www.kcmo.gov/city-hall/departments/city-planning-development',
    climateZones: ['Cold winter', 'Humid summer', 'Zone 5'],
    medianHomeValue: '$250,000', typicalSqft: '1,500',
    commonArchitecturalStyles: ['Colonial', 'Ranch', 'Craftsman', 'Bungalow'],
    featuredGuides: [],
    imagePrompt: 'A Colonial revival home with stone facade in the Country Club District of Kansas City',
  },
  {
    slug: 'atlanta', name: 'Atlanta', state: 'Georgia', stateAbbr: 'GA',
    population: 498715, region: 'South', costIndex: 1.10,
    description: 'Atlanta has a diverse housing stock from Victorian homes in Inman Park and Craftsman bungalows in Kirkwood to mid-century ranches and new infill construction. The Office of Buildings handles permits. Clay soil foundations, humidity-driven mold issues, and steep lot grading are common renovation challenges.',
    permitAuthority: 'Atlanta Office of Buildings', permitUrl: 'https://www.atlantaga.gov/government/departments/office-of-buildings',
    climateZones: ['Humid subtropical', 'Hot summer', 'Mild winter', 'Zone 4'],
    medianHomeValue: '$410,000', typicalSqft: '1,600',
    commonArchitecturalStyles: ['Victorian', 'Craftsman', 'Ranch', 'Contemporary'],
    featuredGuides: ['kitchen-remodel-cost', 'interior-painting-cost'],
    imagePrompt: 'A Craftsman bungalow with front porch and magnolia trees in Atlanta',
  },
  {
    slug: 'omaha', name: 'Omaha', state: 'Nebraska', stateAbbr: 'NE',
    population: 486286, region: 'Midwest', costIndex: 0.85,
    description: 'Omaha blends historic neighborhoods like the Dundee-Memorial Park area with mid-century ranches and growing suburban subdivisions. The Planning Department handles permits. Harsh winters create a condensed outdoor construction window.',
    permitAuthority: 'Omaha Planning Department', permitUrl: 'https://www.cityofomaha.org/planning',
    climateZones: ['Cold winter', 'Humid summer', 'Zone 5'],
    medianHomeValue: '$245,000', typicalSqft: '1,500',
    commonArchitecturalStyles: ['Colonial', 'Ranch', 'Craftsman', 'Bungalow'],
    featuredGuides: [],
    imagePrompt: 'A Colonial style home with white siding and front porch in Omaha',
  },
  {
    slug: 'colorado-springs', name: 'Colorado Springs', state: 'Colorado', stateAbbr: 'CO',
    population: 478961, region: 'West', costIndex: 1.05,
    description: 'Colorado Springs has ranch and contemporary homes set against the Front Range of the Rockies. The Building Division handles permits. High-altitude sun exposure, freeze-thaw cycles, and wildfire mitigation requirements are unique renovation factors.',
    permitAuthority: 'Colorado Springs Building Division', permitUrl: 'https://coloradosprings.gov/building',
    climateZones: ['Semi-arid', 'Cold winter', 'Mild summer', 'Zone 5'],
    medianHomeValue: '$420,000', typicalSqft: '1,700',
    commonArchitecturalStyles: ['Ranch', 'Contemporary', 'Mid-century', 'Mountain Contemporary'],
    featuredGuides: [],
    imagePrompt: 'A ranch style home with mountain views in Colorado Springs',
  },
  {
    slug: 'raleigh', name: 'Raleigh', state: 'North Carolina', stateAbbr: 'NC',
    population: 474069, region: 'South', costIndex: 1.00,
    description: 'Raleigh is a growing tech hub with historic bungalows in Five Points and Oakwood, mid-century homes in the central neighborhoods, and extensive new construction in the suburbs. The Inspections Department handles permits. High humidity and pine beetle issues affect exterior work.',
    permitAuthority: 'Raleigh Inspections Department', permitUrl: 'https://raleighnc.gov/inspections',
    climateZones: ['Humid subtropical', 'Hot summer', 'Mild winter', 'Zone 4'],
    medianHomeValue: '$375,000', typicalSqft: '1,600',
    commonArchitecturalStyles: ['Colonial', 'Craftsman', 'Ranch', 'Bungalow'],
    featuredGuides: ['interior-painting-cost'],
    imagePrompt: 'A Craftsman bungalow with front porch and hardwood trees in Raleigh',
  },
  {
    slug: 'long-beach', name: 'Long Beach', state: 'California', stateAbbr: 'CA',
    population: 466742, region: 'Pacific', costIndex: 1.50,
    description: 'Long Beach has a mix of Craftsman bungalows, Spanish colonial revival homes, mid-century moderns, and beachfront condos. The Development Services Department handles permits. Coastal proximity brings corrosion concerns and additional commission requirements.',
    permitAuthority: 'Long Beach Development Services Department', permitUrl: 'https://www.longbeach.gov/lbds/',
    climateZones: ['Mediterranean', 'Mild year-round', 'Zone 3'],
    medianHomeValue: '$735,000', typicalSqft: '1,300',
    commonArchitecturalStyles: ['Spanish Revival', 'Craftsman', 'Mid-century Modern', 'Contemporary'],
    featuredGuides: [],
    imagePrompt: 'A Spanish Colonial revival home with red tile roof near the coast in Long Beach',
  },
  {
    slug: 'virginia-beach', name: 'Virginia Beach', state: 'Virginia', stateAbbr: 'VA',
    population: 457672, region: 'South', costIndex: 1.00,
    description: 'Virginia Beach has oceanfront condos, mid-century ranches, and suburban subdivisions along the Atlantic coast. The Building Department handles permits. Flood zones, hurricane preparedness, and wind mitigation requirements significantly affect renovation projects.',
    permitAuthority: 'Virginia Beach Building Department', permitUrl: 'https://www.vbgov.com/government/departments/public-works/permits-inspections/Pages/default.aspx',
    climateZones: ['Humid subtropical', 'Mild winter', 'Hot summer', 'Hurricane risk', 'Zone 4'],
    medianHomeValue: '$365,000', typicalSqft: '1,600',
    commonArchitecturalStyles: ['Colonial', 'Ranch', 'Contemporary', 'Cape Cod'],
    featuredGuides: [],
    imagePrompt: 'A Colonial revival home near the coast in Virginia Beach',
  },
  {
    slug: 'miami', name: 'Miami', state: 'Florida', stateAbbr: 'FL',
    population: 442241, region: 'South', costIndex: 1.45,
    description: 'Miami is known for Art Deco condos, Mediterranean revival estates in Coral Gables, and modern waterfront luxury homes. The Building Department handles permits. Hurricane codes, flood zone restrictions, and termite protection add significant layers to renovation planning.',
    permitAuthority: 'Miami Building Department', permitUrl: 'https://www.miamigov.com/Government/Departments-Organizations/Building-Department',
    climateZones: ['Tropical', 'Hot humid', 'Hurricane risk', 'Zone 4'],
    medianHomeValue: '$575,000', typicalSqft: '1,300',
    commonArchitecturalStyles: ['Art Deco', 'Mediterranean Revival', 'Contemporary', 'Miami Modern'],
    featuredGuides: ['roof-replacement-cost'],
    imagePrompt: 'A pastel Art Deco style building in Miami with palm trees',
  },
  {
    slug: 'oakland', name: 'Oakland', state: 'California', stateAbbr: 'CA',
    population: 440646, region: 'Pacific', costIndex: 1.55,
    description: 'Oakland has Victorian homes, Craftsman bungalows, mid-century moderns, and hillside contemporary builds. The Building Services Division handles permits. Seismic retrofitting is a common renovation cost driver, and hillside properties often require geotechnical work.',
    permitAuthority: 'Oakland Building Services Division', permitUrl: 'https://www.oaklandca.gov/departments/building-services',
    climateZones: ['Mediterranean', 'Mild', 'Zone 3'],
    medianHomeValue: '$785,000', typicalSqft: '1,300',
    commonArchitecturalStyles: ['Victorian', 'Craftsman', 'Mid-century Modern', 'Contemporary'],
    featuredGuides: [],
    imagePrompt: 'A Victorian home with bay windows in Oakland with hills backdrop',
  },
  {
    slug: 'minneapolis', name: 'Minneapolis', state: 'Minnesota', stateAbbr: 'MN',
    population: 429954, region: 'Midwest', costIndex: 1.05,
    description: 'Minneapolis has a range of housing from historic Victorians in the Wedge to Craftsman bungalows and new construction. The CPED handles permits. Brutal winters severely compress the outdoor construction season, and frozen ground affects foundation work from November through March.',
    permitAuthority: 'Minneapolis Community Planning and Economic Development (CPED)', permitUrl: 'https://www.minneapolismn.gov/government/departments/cped/',
    climateZones: ['Cold winter', 'Humid summer', 'Zone 6'],
    medianHomeValue: '$365,000', typicalSqft: '1,400',
    commonArchitecturalStyles: ['Victorian', 'Craftsman', 'Bungalow', 'Mid-century'],
    featuredGuides: ['interior-painting-cost'],
    imagePrompt: 'A Craftsman bungalow with front porch and lake views in Minneapolis',
  },
  {
    slug: 'tampa', name: 'Tampa', state: 'Florida', stateAbbr: 'FL',
    population: 398173, region: 'South', costIndex: 1.00,
    description: 'Tampa has bungalows in historic Hyde Park, mid-century ranches in South Tampa, and sprawling suburban subdivisions. The Construction Services Division handles permits. Hurricane code compliance and moisture control in the humid subtropical climate are recurring themes in renovation work.',
    permitAuthority: 'Tampa Construction Services Division', permitUrl: 'https://www.tampa.gov/construction-services',
    climateZones: ['Humid subtropical', 'Hot summer', 'Hurricane risk', 'Zone 4'],
    medianHomeValue: '$375,000', typicalSqft: '1,500',
    commonArchitecturalStyles: ['Craftsman', 'Ranch', 'Mediterranean Revival', 'Contemporary'],
    featuredGuides: [],
    imagePrompt: 'A Craftsman bungalow with front porch and palm trees in Tampa',
  },
  {
    slug: 'tulsa', name: 'Tulsa', state: 'Oklahoma', stateAbbr: 'OK',
    population: 411867, region: 'South', costIndex: 0.85,
    description: 'Tulsa has Art Deco architecture, historic homes in the Maple Ridge district, and growing suburban communities. The INCOG permits office handles submissions. Severe storm risk, expansive clay soils, and extreme summer temperatures factor heavily into renovation budgets.',
    permitAuthority: 'Tulsa Permitting and Licensing Center', permitUrl: 'https://www.cityoftulsa.org/government/departments/permit-center/',
    climateZones: ['Humid subtropical', 'Hot summer', 'Severe storms', 'Zone 5'],
    medianHomeValue: '$215,000', typicalSqft: '1,500',
    commonArchitecturalStyles: ['Art Deco', 'Colonial', 'Ranch', 'Craftsman'],
    featuredGuides: [],
    imagePrompt: 'An Art Deco style home in Tulsa with manicured lawn',
  },
  {
    slug: 'arlington', name: 'Arlington', state: 'Texas', stateAbbr: 'TX',
    population: 394266, region: 'South', costIndex: 0.90,
    description: 'Arlington is a Dallas-Fort Worth suburb with ranch-style homes, new subdivisions, and townhouses. The Development Services Department handles permits. Foundation issues from expansive clay soil are the most frequent hidden cost in home improvement projects.',
    permitAuthority: 'Arlington Development Services Department', permitUrl: 'https://www.arlingtontx.gov/doing_business/permits_and_inspections',
    climateZones: ['Hot humid', 'Mild winter', 'Zone 4'],
    medianHomeValue: '$315,000', typicalSqft: '1,700',
    commonArchitecturalStyles: ['Ranch', 'Contemporary', 'Colonial'],
    featuredGuides: [],
    imagePrompt: 'A ranch style home with brick exterior and lawn in Arlington Texas',
  },
  {
    slug: 'new-orleans', name: 'New Orleans', state: 'Louisiana', stateAbbr: 'LA',
    population: 383997, region: 'South', costIndex: 0.90,
    description: 'New Orleans has iconic shotgun houses, Creole cottages, and grand mansions in the Garden District. The Safety and Permits Department handles permits. Flood mitigation, termite damage, and historic district commission approvals are defining features of local renovation work.',
    permitAuthority: 'New Orleans Safety and Permits Department', permitUrl: 'https://nola.gov/safety-and-permits/',
    climateZones: ['Humid subtropical', 'Hot summer', 'Hurricane risk', 'Zone 4'],
    medianHomeValue: '$275,000', typicalSqft: '1,400',
    commonArchitecturalStyles: ['Shotgun', 'Creole Cottage', 'Greek Revival', 'Raised Basement'],
    featuredGuides: [],
    imagePrompt: 'A colorful shotgun house with wrought iron details in New Orleans French Quarter',
  },
  {
    slug: 'cleveland', name: 'Cleveland', state: 'Ohio', stateAbbr: 'OH',
    population: 372624, region: 'Midwest', costIndex: 0.75,
    description: 'Cleveland has historic homes in Ohio City and Shaker Heights alongside classic bungalows and postwar ranches. The Building and Housing Department handles permits. Freeze-thaw cycles and aging infrastructure in century homes are the most common challenges faced by renovators.',
    permitAuthority: 'Cleveland Department of Building and Housing', permitUrl: 'https://www.clevelandohio.gov/CityofCleveland/Home/Government/CityAgencies/BuildingHousing',
    climateZones: ['Cold winter', 'Humid summer', 'Lake effect snow', 'Zone 6'],
    medianHomeValue: '$125,000', typicalSqft: '1,400',
    commonArchitecturalStyles: ['Colonial', 'Craftsman', 'Bungalow', 'Victorian'],
    featuredGuides: [],
    imagePrompt: 'A Colonial style home with brick facade in Cleveland near Lake Erie',
  },
];